[phases.setup]
nixPkgs = ["nodejs-18_x", "ffmpeg", "python311", "python311Packages.pip"]

[phases.install]
cmds = [
  "chmod +x scripts/railway-setup.sh",
  "./scripts/railway-setup.sh",
  "npm install"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"